# -*- coding: utf-8 -*-

import sys

# Form implementation generated from reading ui file 'box.py'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt5.QtWidgets import QApplication, QMainWindow, QFileDialog

from fetchWeiboData.main import fetchByPage
from fetchWeiboData.weiboFetch import *


class win(QMainWindow, Ui_Fetch):

    def __init__(self):
        super(win, self).__init__()
        self.setupUi(self)
        self.userName = ""
        self.path = ""
        self.pageNum = 1
        self.pushButton.clicked.connect(self.chooseDir)
        self.pushButton_2.clicked.connect(self.confirm)

    def chooseDir(self):
        self.path = QFileDialog.getExistingDirectory(self, '选择文件夹', "")

    def confirm(self):
        self.userName = self.lineEdit.text()
        self.pageNum = self.lineEdit_2.text()
        fetchByPage(self.userName, self.path, self.pageNum)


if __name__ == '__main__':
    app = QApplication(sys.argv)
    myShow = win()
    myShow.show()
    sys.exit(app.exec_())
